import numpy as np
import numpy.ma as ma

t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print("--------1----------")
# print(t[0:2,1:3])
# print("--------1----------")
# print(t[:,1])
# print("--------1----------")
# print(t[1,:])
# print("--------1----------")
# print(t[:1,2])
# print("--------1----------")
# print(t[:,-1])
# print("--------1----------")
# print(t[:,-2])
# print("--------1----------")
# print(t[:,-2:])
# print("--------1----------")
# print("arg retuer index")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
ma_arr = ma.masked_array(
    arr, mask=[False, False, False, True, True, True, False, False]
)
print(ma_arr.sum())
print(t.sum())
print(t.sum(axis=0))
print(t.sum(axis=1))
print(t.min())
print(t.min(axis=0))
print(t.min(axis=1))
print(t.max())
print(t.max(axis=0))
print(t.max(axis=1))
print(t.argmin())
print(t.argmin(axis=1))
print(t.argmin(axis=0))
print(t.mean())
print(t.mean(axis=1))
print(t.mean(axis=0))
print(t.std())
print(t.std(axis=1))
print(t.std(axis=0))
print(t.var())
print(t.var(axis=1))
print(t.var(axis=0))
print("------------nan ------------")
t[0, 1] = np.nan
print(t)
print(np.nanmin(t))
